name: flasksnap # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: the best snap evar
description: |
  I like apps that work

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots


apps:
  flasksnap:
    command: python3 $SNAP/app.py
    daemon: simple
    plugs:
      - network
      - network-bind
      - network-control
parts:
  flasksnap:
    source: src/flask/
    plugin: dump
    build-packages:
      - python3-pip
      - python3-all
    stage-packages:
      - python3-pip
      - python3-all
    override-build: |
      snapcraftctl build
      pip3 install flask
  hooks:
    plugin: dump
    source: src/hooks/
    organize:
      bin/: snap/hooks/
